INSERT INTO
    STUDENT_ANSWERS (ATTEMPT_ID, QUESTION_ID, ANSWER_DATA, POINTS, FEEDBACK)
VALUES
    ($1, $2, $3, $4, $5)
ON CONFLICT (ATTEMPT_ID, QUESTION_ID)
DO UPDATE SET
    ANSWER_DATA = EXCLUDED.ANSWER_DATA,
    POINTS = EXCLUDED.POINTS,
    FEEDBACK = COALESCE(EXCLUDED.FEEDBACK, STUDENT_ANSWERS.FEEDBACK)
RETURNING
    ID,
    ATTEMPT_ID AS "attemptId",
    QUESTION_ID AS "questionId",
    ANSWER_DATA AS "answerData",
    CREATED_AT AS "createdAt",
    POINTS,
    FEEDBACK;