UPDATE QUESTION_OPTIONS
SET
    QUESTION_ID = COALESCE($2, QUESTION_ID),
    OPTION_TEXT = COALESCE($3, OPTION_TEXT),
    IS_CORRECT = COALESCE($4, IS_CORRECT)
WHERE
    ID = $1 RETURNING ID,
    QUESTION_ID AS "questionId",
    OPTION_TEXT AS "optionText",
    IS_CORRECT AS "isCorrect",
    CREATED_AT AS "createdAt";