WITH
	UPDATED_ATTEMPT AS (
		UPDATE QUIZ_ATTEMPTS
		SET
			COMPLETED_AT = CURRENT_TIMESTAMP,
			POINTS = COALESCE(
				(
					SELECT
						SUM(COALESCE(POINTS, 0))
					FROM
						student_answers
					WHERE
						ATTEMPT_ID = $1
				),
				0
			)
		WHERE
			ID = $1
			AND COMPLETED_AT IS NULL
		RETURNING
			ID,
			USER_ID,
			QUIZ_ID,
			POINTS,
			STARTED_AT,
			COMPLETED_AT
	),
	COMPLETED_ASSIGNMENT AS (
		UPDATE ASSIGNMENT_ITEMS AI
		SET
			STATUS = 'completed'
		FROM
			ASSIGNMENTS A,
			UPDATED_ATTEMPT UA
		WHERE
			AI.ASSIGNMENT_ID = A.ID
			AND A.USER_ID = UA.USER_ID
			AND AI.CONTENT_TYPE = 'quiz'
			AND AI.CONTENT_ID = UA.QUIZ_ID
			AND AI.STATUS <> 'completed'
	)
SELECT
	ID AS "id",
	USER_ID AS "userId",
	QUIZ_ID AS "quizId",
	POINTS AS "points",
	STARTED_AT AS "startedAt",
	COMPLETED_AT AS "completedAt"
FROM
	UPDATED_ATTEMPT;