UPDATE QUIZ_ATTEMPTS
SET
    QUIZ_ID = COALESCE($2, QUIZ_ID),
    USER_ID = COALESCE($3, USER_ID),
    POINTS = COALESCE($4, POINTS),
    STARTED_AT = COALESCE($5, STARTED_AT),
    COMPLETED_AT = COALESCE($6, COMPLETED_AT)
WHERE
    ID = $1 RETURNING ID,
    USER_ID AS "userId",
    QUIZ_ID AS "quizId",
    POINTS,
    STARTED_AT AS "startedAt",
    COMPLETED_AT AS "completedAt";