SELECT
    VTW.ID,
    VTW.VOCABULARY_ID AS "vocabularyId",
    VTW.TOPIC_ID AS "topicId",
    V.WORD,
    V.MEANING,
    V.EXAMPLE,
    V.TRANSLATION,
    VT.TOPIC,
    VTW.CREATED_AT AS "createdAt"
FROM
    VOCABULARY_TOPIC_WORDS VTW
    JOIN VOCABULARY V ON VTW.VOCABULARY_ID = V.ID
    JOIN VOCABULARY_TOPICS VT ON VTW.TOPIC_ID = VT.ID
WHERE
    VTW.ID = $1;