INSERT INTO
	AI_DRAFTS (MODEL, DRAFT, DRAFT_TYPE, IS_APPROVED, ADDITIONAL_INSTRUCTIONS)
VALUES
	($1, $2, $3, $4, $5)
RETURNING
	ID,
	MODEL AS "model",
	DRAFT AS "draft",
	IS_APPROVED AS "isApproved",
	ADDITIONAL_INSTRUCTIONS AS "additionalInstructions",
	CREATED_AT AS "createdAt";