WITH
	USER_QUIZZES AS (
		SELECT
			AI.CONTENT_ID AS QUIZ_ID,
			AI.IS_COMPLETED
		FROM
			ASSIGNMENT_ITEMS AI
			JOIN ASSIGNMENTS A ON AI.ASSIGNMENT_ID = A.ID
		WHERE
			A.USER_ID = $1
			AND A.IS_COMPLETED = FALSE
			AND AI.CONTENT_TYPE = 'quiz'
	),
	LATEST_ATTEMPTS AS (
		SELECT DISTINCT
			ON (QUIZ_ID) ID AS ATTEMPT_ID,
			QUIZ_ID,
			COMPLETED_AT
		FROM
			QUIZ_ATTEMPTS
		WHERE
			USER_ID = $1
		ORDER BY
			QUIZ_ID,
			STARTED_AT DESC
	),
	QUIZ_TOTALS AS (
		SELECT
			QUIZ_ID,
			COUNT(ID) AS TOTAL_QUESTIONS
		FROM
			QUIZ_QUESTIONS
		GROUP BY
			QUIZ_ID
	),
	ATTEMPT_ANSWERS AS (
		SELECT
			ATTEMPT_ID,
			COUNT(DISTINCT QUESTION_ID) AS ANSWERED_QUESTIONS
		FROM
			student_answers
		GROUP BY
			ATTEMPT_ID
	)
SELECT
	UQ.QUIZ_ID AS "quizId",
	UQ.IS_COMPLETED AS "assignmentStatus",
	LA.COMPLETED_AT AS "completedAt",
	COALESCE(QT.TOTAL_QUESTIONS, 0)::INT AS "totalQuestions",
	COALESCE(AA.ANSWERED_QUESTIONS, 0)::INT AS "answeredQuestions"
FROM
	USER_QUIZZES UQ
	LEFT JOIN LATEST_ATTEMPTS LA ON UQ.QUIZ_ID = LA.QUIZ_ID
	LEFT JOIN QUIZ_TOTALS QT ON UQ.QUIZ_ID = QT.QUIZ_ID
	LEFT JOIN ATTEMPT_ANSWERS AA ON LA.ATTEMPT_ID = AA.ATTEMPT_ID;