SELECT
	AI.CONTENT_TYPE AS "contentType",
	COUNT(*)::INT AS "totalItems",
	COUNT(*) FILTER (
		WHERE
			AI.STATUS = 'completed'
	)::INT AS "completedItems"
FROM
	PUBLIC.ASSIGNMENT_ITEMS AI
	JOIN PUBLIC.ASSIGNMENTS A ON AI.ASSIGNMENT_ID = A.ID
WHERE
	A.USER_ID = $1
	AND A.STATUS = 'assigned'
GROUP BY
	AI.CONTENT_TYPE;