UPDATE ANSWERS
SET
    QUESTION_ID = COALESCE($2, QUESTION_ID),
    ANSWER = COALESCE($3, ANSWER),
    BLANK_INDEX = COALESCE($4, BLANK_INDEX)
WHERE
    ID = $1 RETURNING ID,
    QUESTION_ID AS "questionId",
    ANSWER,
    BLANK_INDEX AS "blankIndex",
    CREATED_AT AS "createdAt";