SELECT
	U.ID,
	U.NAME,
	U.EMAIL,
	U.PASSWORD,
	U.ROLE,
	T.NAME AS "teacherName",
	T.EMAIL AS "teacherEmail",
	U.CREATED_AT AS "createdAt"
FROM
	USERS U
	LEFT JOIN USERS T ON T.ID = U.TEACHER_ID
ORDER BY
	U.NAME ASC;