SELECT
	U.ID,
	U.NAME,
	U.EMAIL,
	U.PASSWORD,
	U.ROLE,
	T.ID AS "teacherId",
	T.NAME AS "teacherName",
	T.EMAIL AS "teacherEmail",
	U.IS_APPROVED AS "isApproved",
	U.CREATED_AT AS "createdAt"
FROM
	USERS U
	LEFT JOIN USERS T ON T.ID = U.TEACHER_ID
WHERE
	U.EMAIL = $1;