INSERT INTO
	AI_CONTENTS (MODEL, CONTENT, CONTENT_TYPE, IS_APPROVED, ADDITIONAL_INSTRUCTIONS)
VALUES
	($1, $2, $3, $4, $5)
RETURNING
	ID,
	MODEL AS "model",
	CONTENT AS "content",
	IS_APPROVED AS "isApproved",
	ADDITIONAL_INSTRUCTIONS AS "additionalInstructions",
	CREATED_AT AS "createdAt";