SELECT
	QQ.MAX_POINTS AS "maxPoints",
	QO.ID::TEXT AS "correctOptionId"
FROM
	QUIZ_ATTEMPTS QA
	INNER JOIN QUIZ_QUESTIONS QQ ON QQ.QUIZ_ID = QA.QUIZ_ID
	INNER JOIN QUESTION_CHOICES QO ON QO.QUESTION_ID = QQ.QUESTION_ID
WHERE
	QA.ID = $1
	AND QQ.QUESTION_ID = $2
	AND QO.IS_CORRECT = TRUE;