INSERT INTO
	PUBLIC.student_answers (
		ATTEMPT_ID,
		QUESTION_ID,
		BLANK_INDEX,
		SELECTED_OPTION_ID,
		TEXT_ANSWER,
		POINTS
	)
SELECT
	$1,
	$2,
	DATA.BLANK_INDEX,
	DATA.OPTION_ID,
	DATA.TEXT_ANS,
	DATA.PTS
FROM
	UNNEST(
		$3::NUMERIC[],
		$4::UUID[],
		$5::TEXT[],
		$6::NUMERIC[]
	) AS DATA (BLANK_INDEX, OPTION_ID, TEXT_ANS, PTS)
ON CONFLICT (ATTEMPT_ID, QUESTION_ID, BLANK_INDEX) DO UPDATE
SET
	SELECTED_OPTION_ID = EXCLUDED.SELECTED_OPTION_ID,
	TEXT_ANSWER = EXCLUDED.TEXT_ANSWER,
	POINTS = EXCLUDED.POINTS,
	CREATED_AT = NOW()
RETURNING
	ID,
	ATTEMPT_ID AS "attemptId",
	QUESTION_ID AS "questionId",
	BLANK_INDEX AS "blankIndex",
	SELECTED_OPTION_ID AS "selectedOptionId",
	TEXT_ANSWER AS "textAnswer",
	POINTS,
	CREATED_AT AS "createdAt";